services:
  - type: web
    name: recetas-magicas-api
    rootDir: API
    buildCommand: ""
    startCommand: ""
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MYSQL_HOST
        value: mysql.railway.internal
      - key: MYSQL_PORT
        value: 3306
      - key: MYSQL_DATABASE
        value: railway
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: hZhaPaXgOQYzhUdeUzkOWkUtyFvVTgyZ
